[package]
name = "parse"
version = "0.1.0"
authors = ["gl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_error = "1.7.1"
byteorder = "1.3.2"
