[package]
name = "parse"
version = "0.1.0"
authors = ["gl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_error = "1.7.1"
structopt = "0.3"
byteorder = "1.3.2"
image = "0.22.2"
hex = "0.3.2"
